/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package harvestword;

import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author caballeroda_sd2081
 */
public class WordCounter extends javax.swing.JFrame {

    int daine = 0;
    List<String> list = new ArrayList();
    List<String> listRemove = new ArrayList();
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/dainedb";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "";

    public Object[][] RetrieveData() {
        Object[][] data = new Object[daine][4];
        Connection conn = null;
        Statement stmt = null;
        String retrieveQuery;
        retrieveQuery = String.format("SELECT * from `datacollect`");
        try {
            int cols = 0;
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(retrieveQuery);
            System.out.println(rs);
            while (rs.next()) {
                data[cols][0] = rs.getInt("Id");
                data[cols][1] = rs.getString("Word");
                data[cols][2] = rs.getInt("Count");
                data[cols][3] = rs.getString("School");
                ++cols;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            String checkQuery = "Select word from `datacollect`";
        }
        return data;
    }

    /**
     * Creates new form WordCounter
     */
    public WordCounter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        removeTags = new javax.swing.JButton();
        countWord = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        removeTags1 = new javax.swing.JButton();
        countWord1 = new javax.swing.JButton();
        showResult = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRemove = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Input text here......");

        removeTags.setText("Remove Tags");
        removeTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTagsActionPerformed(evt);
            }
        });

        countWord.setText("Count");
        countWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countWordMouseClicked(evt);
            }
        });
        countWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countWordActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Word Counter");
        jLabel1.setMaximumSize(new java.awt.Dimension(69, 20));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Input text here......");

        inputText.setBackground(new java.awt.Color(255, 204, 255));
        inputText.setColumns(20);
        inputText.setRows(5);
        jScrollPane1.setViewportView(inputText);

        removeTags1.setText("Remove Tags");
        removeTags1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTags1ActionPerformed(evt);
            }
        });

        countWord1.setText("Count");
        countWord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countWord1MouseClicked(evt);
            }
        });
        countWord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countWord1ActionPerformed(evt);
            }
        });

        showResult.setText("Show");
        showResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultActionPerformed(evt);
            }
        });

        jTextAreaRemove.setBackground(new java.awt.Color(255, 204, 255));
        jTextAreaRemove.setColumns(20);
        jTextAreaRemove.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRemove);

        jLabel5.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Result");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(removeTags1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(countWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(showResult, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeTags1)
                    .addComponent(countWord1)
                    .addComponent(showResult))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTagsActionPerformed
        
    }//GEN-LAST:event_removeTagsActionPerformed

    private void removeTags1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTags1ActionPerformed
        jTextAreaRemove.setText("");
        String str = inputText.getText();
        removeTags f = new removeTags();
        str = f.removeHTML(str);
        str = str.replaceAll("\\s+", " ");
        String output = "";

        String[] loop = str.split(" ");
        for (String x : loop) {
            if (listRemove.contains(x)) {
                continue;
            } else {
                listRemove.add(x);
            }
        }
        System.out.println(listRemove);
        for (String y : listRemove) {
            output += (y + "\n");
        }
        jTextAreaRemove.setText(output);
    }//GEN-LAST:event_removeTags1ActionPerformed

    private void countWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countWordMouseClicked
       
    }//GEN-LAST:event_countWordMouseClicked

    private void countWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countWordActionPerformed

    private void countWord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countWord1MouseClicked
        jTextAreaRemove.setText("");
        String str = inputText.getText();
        removeTags f = new removeTags();
        str = f.removeHTML(str);
        str = str.replaceAll("\\s+", " ");
        String output = "";

        Connection conn = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected successfully...");

            //STEP 4: Execute a query
            System.out.println(" \n ");
            System.out.println("Insert records ...");
            stmt = conn.createStatement();

            String[] loop = str.split(" ");
            for (String x : loop) {
                if (list.contains(x)) {
                    continue;
                } else {
                    if (x.equals("")) {
                        continue;
                    } else if (x.contains("'") || x.contains("$")) {
                        continue;
                    } else if (x.length() > 50) {
                        continue;
                    } else {
                        list.add(x);
                    }
                }
            }

            for (String y : list) {
                int counter = 0;
                for (String z : loop) {
                    if (y.equals(z)) {
                        counter++;
                    }
                }
                output += (y + " : " + counter + " , \n");
                String sql = String.format("INSERT INTO datacollect(Word,Count,School) VALUES ('%s','%d','%s')", y, counter, "USC");
                stmt.executeUpdate(sql);
                System.out.println("Insert records ......");
                daine++;
            }
            jTextAreaRemove.setText(output);

        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        } finally {
            //finally block used to close resources
            try {
                if (stmt != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }// do nothing
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }//end finally try
        }//end try
        System.out.println("\nInserted Successfully!");

    }//GEN-LAST:event_countWord1MouseClicked

    private void countWord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countWord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countWord1ActionPerformed

    private void showResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultActionPerformed
        final JFrame frame = new JFrame("JTable Demo");
        String[] columns = {"id", "word", "count", "school"};
        Object[][] data = RetrieveData();
        DefaultTableModel tableModel = new DefaultTableModel(data, columns) {
            public boolean isCellEditable(int row, int column) {
                //all ceisCellEditablells false
                return false;
            }
        };
        this.setVisible(false);
        JTable popUpTable = new JTable(data, columns);
        Font font = new Font("Verdana", Font.PLAIN, 12);
        popUpTable.setModel(tableModel);
        popUpTable.setFont(font);
        popUpTable.setRowHeight(25);
        popUpTable.getTableHeader().setPreferredSize(new Dimension(100, 30));
        popUpTable.getTableHeader().setFont(font);
        JOptionPane.showMessageDialog(null, new JScrollPane(popUpTable), "Word Count", JOptionPane.INFORMATION_MESSAGE
        );
        this.setVisible(true);
    }//GEN-LAST:event_showResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordCounter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countWord;
    private javax.swing.JButton countWord1;
    private javax.swing.JTextArea inputText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaRemove;
    private javax.swing.JButton removeTags;
    private javax.swing.JButton removeTags1;
    private javax.swing.JButton showResult;
    // End of variables declaration//GEN-END:variables
}
